<html>
     <head>
          <title>Create Employee</title>
     </head>
     <body>
     <form action='' method="POST">
          <?php echo $this->employeeForm->getElement('name'); ?>
          <?php echo $this->employeeForm->getElement('number'); ?>
          <?php echo $this->employeeForm->getElement('designation'); ?>
          <?php echo $this->employeeForm->getElement('submit'); ?>
     </form>
     </body>
</html>